eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
microservice:
  payment-service:
   endpoints:
    endpoint: http://PAYMENT-SERVICE/payment/makePayment
  order-service:
   endpoints:
    endpoint: http://ORDER-SERVICE/order/bookOrder
