# microservice:
#   payment-service:
#    endpoints:
#     endpoint: http://PAYMENT-SERVICE/payment/makePayment
#   order-service:
#    endpoints:
#     endpoint: http://ORDER-SERVICE/order/bookOrder

microservice:
  payment-service:
    endpoints:
      endpoint: http://PAYMENT-SERVICE/payment/makePayment
       
  order-service:
    endpoints:
      endpoint: http://ORDER-SERVICE/order/bookOrder
        
